"""
Seed the database with ~50 sample places drawn from the prototype data.
Run once after creating the database:
    python seed_data.py
"""
from app import app, db, Place

SEED_PLACES = [
    {
        "name": "Akiko Tanaka",
        "country": "Japan",
        "place": "Arashiyama Bamboo Grove, Kyoto",
        "flora": ["Moso bamboo", "Japanese maple", "Cherry blossom"],
        "fauna": ["Japanese macaque", "Bush warbler", "Tanuki"],
        "description": "Walking through the towering bamboo, the world falls silent except for the creaking of stalks swaying overhead. Light filters through in shifting columns. I feel impossibly small and completely held at the same time. In autumn, the maples at the grove's edge burn crimson against the green, and I often spot macaques watching from the canopy with calm, knowing eyes.",
        "feeling": "Peaceful and humbled",
        "lat": 35.0094, "lng": 135.6720,
    },
    {
        "name": "Carlos Rivera",
        "country": "Costa Rica",
        "place": "Monteverde Cloud Forest",
        "flora": ["Orchids", "Bromeliads", "Strangler fig"],
        "fauna": ["Resplendent quetzal", "Howler monkey", "Glass frog"],
        "description": "The cloud forest is a world draped in mist. Every surface is alive — mosses, ferns, orchids clinging to branches. When the quetzal appears with its iridescent tail streaming behind, my heart stops. The howler monkeys call across the canopy like distant thunder. I feel like I've stepped into a primordial dream.",
        "feeling": "Awestruck and alive",
        "lat": 10.3058, "lng": -84.8232,
    },
    {
        "name": "Ingrid Svensson",
        "country": "Sweden",
        "place": "Abisko National Park, Swedish Lapland",
        "flora": ["Arctic birch", "Cloudberry", "Reindeer lichen"],
        "fauna": ["Reindeer", "Arctic fox", "Golden eagle"],
        "description": "In winter, the northern lights dance above the frozen lake and the silence is so deep it rings in your ears. In summer, the midnight sun bathes the birch forests in gold for weeks. I come here to feel the vastness of the world and my own smallness within it. The arctic foxes leave delicate tracks in the snow like secret messages.",
        "feeling": "Free and insignificant in the best way",
        "lat": 68.3499, "lng": 18.8297,
    },
    {
        "name": "Amina Diallo",
        "country": "Senegal",
        "place": "Djoudj National Bird Sanctuary",
        "flora": ["Typha reeds", "Water lilies", "Acacia"],
        "fauna": ["White pelican", "Flamingo", "Warthog"],
        "description": "Thousands of pelicans rising together from the water — the sound of their wings is like applause. The wetlands shimmer in the heat, and flamingos stand in impossible pink lines against the green reeds. I grew up near here and every visit reminds me that beauty doesn't need to be discovered, it just needs to be returned to.",
        "feeling": "Rooted and grateful",
        "lat": 16.3333, "lng": -16.2333,
    },
    {
        "name": "James O'Brien",
        "country": "Ireland",
        "place": "Cliffs of Moher, County Clare",
        "flora": ["Sea pink", "Bird's-foot trefoil", "Sea campion"],
        "fauna": ["Atlantic puffin", "Peregrine falcon", "Grey seal"],
        "description": "Standing at the edge with the Atlantic roaring two hundred metres below, the wind so strong it leans you back — there's nothing between you and America. Puffins nest in the cliff face, absurdly colourful against the grey rock. I come here when I need to remember that the world is bigger than my problems.",
        "feeling": "Exhilarated and grounded",
        "lat": 52.9726, "lng": -9.4340,
    },
    {
        "name": "Mei-Ling Chen",
        "country": "Taiwan",
        "place": "Taroko Gorge",
        "flora": ["Camphor tree", "Taiwan red cypress", "Ferns"],
        "fauna": ["Formosan rock macaque", "Mikado pheasant", "Swinhoe's blue pheasant"],
        "description": "The marble walls of the gorge rise hundreds of metres, carved by the Liwu River over millennia. Swallows dart between the cliff faces, and the turquoise water below is so clear it seems unreal. Walking the old trail carved into the rock, I feel connected to every person who has ever walked this path before me.",
        "feeling": "Connected to deep time",
        "lat": 24.1577, "lng": 121.6266,
    },
    {
        "name": "Oluwaseun Adeyemi",
        "country": "Nigeria",
        "place": "Omo Forest Reserve",
        "flora": ["Mahogany", "Iroko tree", "Oil palm"],
        "fauna": ["Forest elephant", "Chimpanzee", "Grey parrot"],
        "description": "The canopy is so thick that noon feels like dusk. You hear the forest before you see it — the crash of something large moving through undergrowth, the cascading call of grey parrots. Finding chimp nests high in the mahogany trees fills me with hope. This forest is fighting to survive, and so am I.",
        "feeling": "Determined and hopeful",
        "lat": 6.6167, "lng": 4.7167,
    },
    {
        "name": "Elena Petrova",
        "country": "Russia",
        "place": "Lake Baikal, Siberia",
        "flora": ["Siberian pine", "Rhododendron", "Sphagnum moss"],
        "fauna": ["Baikal seal", "Omul fish", "Sable"],
        "description": "In winter, the lake freezes into glass so clear you can see forty metres down. Cracks sing across the ice like whale song. The Baikal seals — found nowhere else on Earth — pop up through breathing holes and regard you with enormous dark eyes. I have never felt more present than on that ice, with the oldest lake in the world beneath my feet.",
        "feeling": "Profoundly present",
        "lat": 53.5587, "lng": 108.1650,
    },
    {
        "name": "Lucas Martínez",
        "country": "Argentina",
        "place": "Los Glaciares National Park, Patagonia",
        "flora": ["Lenga beech", "Calafate bush", "Antarctic moss"],
        "fauna": ["Andean condor", "Guanaco", "Patagonian fox"],
        "description": "Perito Moreno glacier creaks and groans like a living thing. Every few minutes, a house-sized chunk of ice calves into the lake with a sound like thunder. Condors circle above on thermals, barely moving their wings. The calafate berries are everywhere — legend says if you eat them, you'll always return. I have eaten many.",
        "feeling": "Overwhelmed by scale",
        "lat": -50.6500, "lng": -73.0000,
    },
    {
        "name": "Fatima Al-Rashid",
        "country": "Oman",
        "place": "Wadi Shab",
        "flora": ["Date palm", "Oleander", "Wild fig"],
        "fauna": ["Arabian tahr", "Bonelli's eagle", "Blue-cheeked bee-eater"],
        "description": "You walk through a narrow canyon with turquoise pools linked by short swims, and suddenly you're inside a cave with a waterfall pouring from the ceiling. Date palms cling to the cliff edges, and bee-eaters flash past in streaks of green and blue. It feels like finding a secret that the desert has been keeping for thousands of years.",
        "feeling": "Wonder and discovery",
        "lat": 22.8569, "lng": 59.2847,
    },
    {
        "name": "Sophie Dubois",
        "country": "France",
        "place": "Camargue Wetlands",
        "flora": ["Samphire", "Sea lavender", "Tamarisk"],
        "fauna": ["Greater flamingo", "Camargue horse", "European bee-eater"],
        "description": "The white horses gallop through shallow lagoons, sending up sprays of silver water. Flamingos turn the horizon pink. The light here is unlike anywhere else in France — it has a luminous, almost liquid quality. The salt marshes stretch endlessly, and the wind carries the scent of lavender and brine. I feel untethered from time.",
        "feeling": "Timeless and dreamy",
        "lat": 43.5333, "lng": 4.5667,
    },
    {
        "name": "Kofi Mensah",
        "country": "Ghana",
        "place": "Kakum National Park",
        "flora": ["African mahogany", "Epiphytic orchids", "Oil palm"],
        "fauna": ["Diana monkey", "Forest elephant", "Hornbill"],
        "description": "Walking the canopy walkway forty metres above the forest floor, swaying between giant trees, you see the forest as the birds see it. Hornbills glide below you. The sound is extraordinary — a wall of insect song punctuated by monkey calls. Up here, suspended between earth and sky, I feel utterly free.",
        "feeling": "Liberated and joyful",
        "lat": 5.3453, "lng": -1.3864,
    },
    {
        "name": "Yuki Nakamura",
        "country": "Japan",
        "place": "Yakushima Island",
        "flora": ["Ancient cedar (Yakusugi)", "Moss", "Rhododendron"],
        "fauna": ["Yakushima macaque", "Yakushima deer", "Loggerhead turtle"],
        "description": "The cedar trees here are thousands of years old, their trunks twisted into impossible shapes, every surface carpeted in moss so green it almost glows. Rain falls more days than not, and it makes everything luminous. Walking among these ancient trees, I feel the weight and beauty of deep time. They were old when Rome was young.",
        "feeling": "Reverent and small",
        "lat": 30.3700, "lng": 130.6500,
    },
    {
        "name": "Priya Sharma",
        "country": "India",
        "place": "Valley of Flowers, Uttarakhand",
        "flora": ["Brahma kamal", "Blue poppy", "Cobra lily"],
        "fauna": ["Snow leopard", "Himalayan monal", "Musk deer"],
        "description": "After days of trekking through bare mountain, you crest a ridge and suddenly the entire valley is carpeted in wildflowers — hundreds of species in every colour imaginable. Himalayan monals strut through the meadows, their feathers catching the sun like jewels. The air is thin and sweet. I wept the first time I saw it.",
        "feeling": "Ecstatic and emotional",
        "lat": 30.7280, "lng": 79.6052,
    },
    {
        "name": "Marco Bianchi",
        "country": "Italy",
        "place": "Matera, Basilicata",
        "flora": ["Wild thyme", "Caper bush", "Prickly pear"],
        "fauna": ["Lesser kestrel", "Italian wall lizard", "European bee-eater"],
        "description": "The sassi — ancient cave dwellings carved into limestone — cascade down the ravine like a stone waterfall. Kestrels nest in the abandoned caves and hunt over the gorge at sunset. Wild thyme and capers grow from every crack. Walking these streets, some of the oldest continuously inhabited places on Earth, I feel the layers of human persistence.",
        "feeling": "Awed by human endurance",
        "lat": 40.6656, "lng": 16.6043,
    },
    {
        "name": "Aisha Mohammed",
        "country": "Kenya",
        "place": "Maasai Mara",
        "flora": ["Red oat grass", "Balanites tree", "Croton bush"],
        "fauna": ["Wildebeest", "Lion", "Lilac-breasted roller"],
        "description": "During the great migration, the plains darken with wildebeest as far as the eye can see. The sound — a constant low rumbling — fills the air like distant surf. Lions watch from the shade of balanites trees. A lilac-breasted roller perches on a branch, impossibly beautiful against the golden grass. This is life at its most raw and magnificent.",
        "feeling": "Alive and electric",
        "lat": -1.5000, "lng": 35.1500,
    },
    {
        "name": "Henrik Johansson",
        "country": "Norway",
        "place": "Lofoten Islands",
        "flora": ["Arctic poppy", "Mountain avens", "Crowberry"],
        "fauna": ["White-tailed eagle", "Atlantic puffin", "Orca"],
        "description": "Jagged peaks rise straight from a sea that shifts between steel grey and impossible turquoise. The fishing villages are dots of red and yellow against the mountains. In winter, the northern lights reflect off the water. I once watched a white-tailed eagle pluck a fish from the fjord — effortless, precise, wild. This place makes me believe in untamed things.",
        "feeling": "Wild and inspired",
        "lat": 68.1100, "lng": 13.9000,
    },
    {
        "name": "Maria Santos",
        "country": "Brazil",
        "place": "Chapada Diamantina, Bahia",
        "flora": ["Bromeliad", "Candeia tree", "Sempre-viva flower"],
        "fauna": ["Maned wolf", "Hyacinth macaw", "Black-chested buzzard eagle"],
        "description": "Tabletop mountains rise from the cerrado like ancient monuments. Hidden caves hold crystal-clear pools, and waterfalls plunge into canyons so deep the bottom is in perpetual twilight. Hyacinth macaws — the world's largest parrot — fly overhead in pairs, their calls echoing off stone. I feel like an explorer finding lost worlds.",
        "feeling": "Adventurous and amazed",
        "lat": -12.4667, "lng": -41.4833,
    },
    {
        "name": "Tenzin Dorje",
        "country": "Nepal",
        "place": "Annapurna Sanctuary",
        "flora": ["Rhododendron", "Blue pine", "Juniper"],
        "fauna": ["Himalayan tahr", "Danphe pheasant", "Lammergeier"],
        "description": "The amphitheatre of peaks — Annapurna, Machapuchare, Hiunchuli — surrounds you on all sides, all above 6,000 metres. Prayer flags snap in the wind. The rhododendrons bloom red against the snow in spring. A lammergeier soars overhead, carrying a bone to drop on the rocks below. In this natural cathedral, I feel held by the mountains.",
        "feeling": "Protected and spiritual",
        "lat": 28.5000, "lng": 83.8700,
    },
    {
        "name": "Sarah Mitchell",
        "country": "Australia",
        "place": "Daintree Rainforest, Queensland",
        "flora": ["Fan palm", "Strangler fig", "King fern"],
        "fauna": ["Cassowary", "Boyd's forest dragon", "Ulysses butterfly"],
        "description": "This is the oldest continuously surviving rainforest on Earth — 180 million years. Meeting a cassowary on the trail, eye to eye with a dinosaur's descendant, the forest suddenly feels like the ancient place it is. Ulysses butterflies — electric blue — drift through the canopy gaps. Where the rainforest meets the reef at Cape Tribulation, two World Heritage sites touch. Nowhere else.",
        "feeling": "Privileged and amazed",
        "lat": -16.1700, "lng": 145.4200,
    },
    {
        "name": "Dmitri Volkov",
        "country": "Russia",
        "place": "Kamchatka Peninsula",
        "flora": ["Stone birch", "Fireweed", "Giant hogweed"],
        "fauna": ["Brown bear", "Steller's sea eagle", "Pacific salmon"],
        "description": "Volcanic peaks steam on the horizon while brown bears fish for salmon in rivers so thick with fish you could almost walk across them. Steller's sea eagles — the largest eagles in the world — perch in the stone birches, watching. The hot springs steam in the cold air. This is the edge of the world, and it is furiously alive.",
        "feeling": "Raw and untamed",
        "lat": 54.0000, "lng": 159.0000,
    },
    {
        "name": "Isabella García",
        "country": "Ecuador",
        "place": "Galápagos Islands",
        "flora": ["Prickly pear cactus", "Scalesia tree", "Mangrove"],
        "fauna": ["Marine iguana", "Blue-footed booby", "Giant tortoise"],
        "description": "The animals here have no fear of humans. A marine iguana sneezes salt on your foot. Blue-footed boobies dance their courtship inches from your face. Giant tortoises move through the highlands with geological patience. Darwin's enchanted islands taught the world about evolution, and standing here, you can feel it — life experimenting, adapting, becoming.",
        "feeling": "Humbled by nature's creativity",
        "lat": -0.9538, "lng": -91.0670,
    },
    {
        "name": "Liam O'Sullivan",
        "country": "New Zealand",
        "place": "Milford Sound, Fiordland",
        "flora": ["Silver beech", "Tree fern", "Rimu"],
        "fauna": ["Fiordland crested penguin", "Bottlenose dolphin", "Kea"],
        "description": "Mitre Peak rises 1,700 metres straight from black water. After rain — and it rains constantly — hundreds of temporary waterfalls pour down the cliffs. Dolphins ride the bow wave of the boat. A kea, the world's only alpine parrot, lands on the railing and tries to steal my sandwich. The scale is impossible and intimate at once.",
        "feeling": "Dwarfed and delighted",
        "lat": -44.6530, "lng": 167.8974,
    },
    {
        "name": "Naomi Okafor",
        "country": "Cameroon",
        "place": "Dja Faunal Reserve",
        "flora": ["African teak", "Sapele mahogany", "Raphia palm"],
        "fauna": ["Western lowland gorilla", "Forest buffalo", "Mandrill"],
        "description": "The forest here is so dense that GPS stops working. You navigate by river and sound. Mandrills — with their extraordinary painted faces — move through the undergrowth in troops of hundreds. Finding gorilla nests in the morning, still warm, knowing they were just here — it makes the forest feel like a shared home.",
        "feeling": "Intimate and wild",
        "lat": 3.3000, "lng": 12.9000,
    },
    {
        "name": "Ana Kovač",
        "country": "Slovenia",
        "place": "Lake Bled",
        "flora": ["European beech", "Linden tree", "Alpine rose"],
        "fauna": ["Alpine ibex", "Golden eagle", "Fire salamander"],
        "description": "The island church floats on emerald water, backed by a medieval castle clinging to a cliff, backed by the Julian Alps capped in snow. It looks like a painting that's trying too hard, but it's real. In autumn, the beeches turn gold and the reflections in the still water are perfect. I row out to the island and ring the wishing bell. I wish to come back.",
        "feeling": "Enchanted and serene",
        "lat": 46.3664, "lng": 14.1138,
    },
    {
        "name": "David Kim",
        "country": "South Korea",
        "place": "Seoraksan National Park",
        "flora": ["Korean pine", "Maple", "Royal azalea"],
        "fauna": ["Asiatic black bear", "Mandarin duck", "Korean goral"],
        "description": "In autumn, the mountains explode into colour — every shade of red, orange, gold, and russet against granite peaks. The morning mist fills the valleys like milk. Mandarin ducks float on impossibly clear streams. At dawn, from Ulsanbawi Rock, you watch the sun rise over the East Sea, and for a moment everything is outlined in gold.",
        "feeling": "Elevated and at peace",
        "lat": 38.1195, "lng": 128.4655,
    },
    {
        "name": "Rosa Flores",
        "country": "Mexico",
        "place": "Monarch Butterfly Reserve, Michoacán",
        "flora": ["Oyamel fir", "Pine", "Wildflowers"],
        "fauna": ["Monarch butterfly", "White-eared hummingbird", "Long-tailed wood partridge"],
        "description": "Millions of monarchs — after flying 4,000 kilometres from Canada — cluster on the oyamel firs so thickly that the branches bend. When the sun warms them, they rise in clouds of orange and black that blot out the sky. The sound of millions of wings is like gentle rain. I cry every single time. It is the most beautiful thing I have ever seen.",
        "feeling": "Overwhelmed with beauty",
        "lat": 19.5667, "lng": -100.2833,
    },
    {
        "name": "Thomas Weber",
        "country": "Germany",
        "place": "Saxon Switzerland, Elbe Sandstone Mountains",
        "flora": ["Scots pine", "Bilberry", "Moss"],
        "fauna": ["Peregrine falcon", "Eurasian lynx", "Fire salamander"],
        "description": "Sandstone pillars rise from ancient forests like the ruins of a giant's castle. The Bastei Bridge spans a gorge 200 metres above the Elbe, and the view stretches to Bohemia. Peregrine falcons nest on the pinnacles. In morning fog, only the tops of the pillars are visible, floating above a white sea. It is Germany's most dramatic secret.",
        "feeling": "Transported to another world",
        "lat": 50.9166, "lng": 14.2333,
    },
    {
        "name": "Leila Ahmadi",
        "country": "Iran",
        "place": "Hyrcanian Forest, Gilan",
        "flora": ["Persian ironwood", "Chestnut-leaved oak", "Box tree"],
        "fauna": ["Persian leopard", "Brown bear", "Caspian red deer"],
        "description": "This forest has survived since the last ice age — a relic of the ancient world clinging to the Caspian shore. The ironwood trees twist into extraordinary shapes, their autumn leaves turning every warm colour. Fog rolls in from the Caspian and the forest becomes a cathedral of dripping green. Knowing that leopards still walk here, unseen, makes every shadow significant.",
        "feeling": "Ancient and mysterious",
        "lat": 37.0000, "lng": 49.5000,
    },
    {
        "name": "Ben Thompson",
        "country": "Canada",
        "place": "Nahanni National Park, Northwest Territories",
        "flora": ["White spruce", "Fireweed", "Labrador tea"],
        "fauna": ["Woodland caribou", "Grizzly bear", "Trumpeter swan"],
        "description": "Virginia Falls drops twice the height of Niagara into a canyon that almost no one will ever see. The South Nahanni River winds through a landscape of hot springs, tufa mounds, and legends of lost gold miners. Grizzlies fish the tributaries. The boreal forest stretches to every horizon. This is wilderness as it was before we named it.",
        "feeling": "Humbled by true wilderness",
        "lat": 61.0000, "lng": -125.0000,
    },
    {
        "name": "Chiara Rossi",
        "country": "Italy",
        "place": "Dolomites, South Tyrol",
        "flora": ["Edelweiss", "Alpine gentian", "Larch"],
        "fauna": ["Chamois", "Marmot", "Bearded vulture"],
        "description": "The Dolomite peaks turn pink at sunset — the Enrosadira — and for twenty minutes the mountains look like they're carved from rose quartz. Marmots whistle warnings across the alpine meadows. Chamois navigate impossible cliff faces with casual grace. In the high meadows, edelweiss grows in secret places. I feel like I'm walking through a fairy tale that happens to be made of stone.",
        "feeling": "Enchanted and breathless",
        "lat": 46.4102, "lng": 11.8440,
    },
    {
        "name": "Kwame Asante",
        "country": "Botswana",
        "place": "Okavango Delta",
        "flora": ["Papyrus", "Water lily", "Sausage tree"],
        "fauna": ["African elephant", "Leopard", "African fish eagle"],
        "description": "A river that never reaches the sea, spreading into a labyrinth of channels and islands in the Kalahari. Gliding by mokoro through papyrus channels, an elephant feeds ten metres away, ignoring you completely. Fish eagles call — that ringing, thrown-back cry. At night, hippos grunt in the darkness. This is Africa at its most generous and indifferent.",
        "feeling": "Quietly thrilled",
        "lat": -19.0000, "lng": 23.0000,
    },
    {
        "name": "Hana Yoshida",
        "country": "Japan",
        "place": "Shiretoko Peninsula, Hokkaido",
        "flora": ["Ezo spruce", "Painted maple", "Skunk cabbage"],
        "fauna": ["Blakiston's fish owl", "Brown bear", "Steller's sea eagle"],
        "description": "At the edge of Japan, where pack ice drifts down from Russia, the largest owls in the world hunt along frozen streams. Bears catch salmon in waterfalls. Steller's sea eagles — massive, black and white — gather on the ice floes by the hundreds. Shiretoko means 'the end of the earth' in Ainu. It feels exactly like that.",
        "feeling": "At the world's edge",
        "lat": 44.2000, "lng": 145.0000,
    },
    {
        "name": "Emma Larsson",
        "country": "Sweden",
        "place": "Gotland Island",
        "flora": ["Wild orchid", "Sea buckthorn", "Raukar stone formations with lichen"],
        "fauna": ["Gotland pony", "Guillemot", "Hedgehog"],
        "description": "The raukar — limestone sea stacks shaped by millennia of waves — stand along the coast like abstract sculptures. More wild orchid species grow here than almost anywhere in Europe. The medieval town of Visby feels like stepping through a portal. In summer, the light lasts until midnight and the meadows buzz with life. It is Sweden's quiet magic.",
        "feeling": "Enchanted and curious",
        "lat": 57.4684, "lng": 18.4867,
    },
    {
        "name": "André Nkomo",
        "country": "South Africa",
        "place": "Kirstenbosch and Table Mountain, Cape Town",
        "flora": ["King protea", "Silver tree", "Fynbos"],
        "fauna": ["Rock hyrax (dassie)", "Sunbird", "Chacma baboon"],
        "description": "Table Mountain's flat summit holds a world of fynbos — the richest plant kingdom on Earth compressed into a tiny area. King proteas bloom like alien crowns. Sunbirds hover at flowers with iridescent precision. The view from the top — two oceans meeting — reminds you that this is where the continent ends and something else begins.",
        "feeling": "Proud and inspired",
        "lat": -33.9625, "lng": 18.4097,
    },
    {
        "name": "Catherine Tremblay",
        "country": "Canada",
        "place": "Bay of Fundy, New Brunswick",
        "flora": ["Dulse seaweed", "Rockweed", "Balsam fir"],
        "fauna": ["North Atlantic right whale", "Atlantic puffin", "Bald eagle"],
        "description": "The highest tides in the world — 16 metres — reveal a vast seafloor of sculpted rock at low tide, then swallow it whole six hours later. Kayaking at high tide, right whales surface so close the spray hits your face. The Hopewell Rocks stand like flowerpots carved by the sea. Time here is measured in tides, not hours.",
        "feeling": "In rhythm with something ancient",
        "lat": 45.3500, "lng": -64.5200,
    },
    {
        "name": "Rashid Hassan",
        "country": "Morocco",
        "place": "Todra Gorge, Atlas Mountains",
        "flora": ["Date palm", "Fig tree", "Oleander"],
        "fauna": ["Barbary macaque", "Bonelli's eagle", "Atlas mountain viper"],
        "description": "The gorge narrows until the walls are only ten metres apart and 300 metres high, and the strip of sky above is blinding blue. Date palms somehow grow at the base, fed by the river. Bonelli's eagles nest on ledges you can barely see. The Amazigh villages at the gorge mouth have been here for centuries, built from the same red stone. I feel sheltered by geology.",
        "feeling": "Sheltered and awed",
        "lat": 31.5853, "lng": -5.5861,
    },
    {
        "name": "Linh Nguyen",
        "country": "Vietnam",
        "place": "Ha Long Bay",
        "flora": ["Mangrove", "Cycad", "Tropical orchid"],
        "fauna": ["Cat Ba langur", "Hawksbill turtle", "White-bellied sea eagle"],
        "description": "Nearly two thousand limestone karsts rise from emerald water, each topped with jungle. Fishing boats thread between them. Caves hide inside the islands — vast cathedral spaces of stalactites. At dawn, the mist sits between the karsts and everything turns to silhouette and suggestion. It looks like a Chinese painting come to life, which of course is the other way around.",
        "feeling": "Floating between worlds",
        "lat": 20.9101, "lng": 107.1839,
    },
    {
        "name": "João Silva",
        "country": "Portugal",
        "place": "Azores, São Miguel Island",
        "flora": ["Hydrangea", "Laurel", "Japanese cedar"],
        "fauna": ["Sperm whale", "Cory's shearwater", "Azores bullfinch"],
        "description": "Volcanic crater lakes — one green, one blue — sit side by side in Sete Cidades, ringed by hydrangeas. Out at sea, sperm whales dive in water a thousand metres deep just kilometres from shore. At night, shearwaters return to their burrows, calling in the darkness. The Azores feel like the middle of nowhere and the centre of everything.",
        "feeling": "Remote and complete",
        "lat": 37.7412, "lng": -25.6756,
    },
    {
        "name": "Grace Wanjiku",
        "country": "Kenya",
        "place": "Lake Nakuru",
        "flora": ["Yellow-barked acacia", "Euphorbia", "Candelabra tree"],
        "fauna": ["Lesser flamingo", "White rhino", "Rothschild's giraffe"],
        "description": "Two million flamingos turn the lake into a living pink carpet. When they take flight, the sky fills with colour and the sound of wings is like rushing water. White rhinos graze in the fever tree forest, guarded by rangers. Rothschild's giraffes — fewer than a thousand left — move through the acacias with impossible elegance. Every visit feels urgent and precious.",
        "feeling": "Urgent love",
        "lat": -0.3700, "lng": 36.0900,
    },
    {
        "name": "Sebastian Müller",
        "country": "Germany",
        "place": "Black Forest, Baden-Württemberg",
        "flora": ["Silver fir", "Bilberry", "Foxglove"],
        "fauna": ["Black woodpecker", "European badger", "Red deer"],
        "description": "The forest is so dense and the firs so tall that the floor is a twilight world of moss and ferns. Black woodpeckers drum on dead trees — a sound like slow machine-gun fire. The trails wind through tiny valleys with streams cold enough to ache. In autumn, fog fills the valleys and only the hilltops emerge. It is every fairy tale's setting, and it knows it.",
        "feeling": "Storied and calm",
        "lat": 47.8720, "lng": 8.2041,
    },
    {
        "name": "Arundhati Nair",
        "country": "India",
        "place": "Sundarbans, West Bengal",
        "flora": ["Sundari tree", "Mangrove", "Nipa palm"],
        "fauna": ["Bengal tiger", "Gangetic dolphin", "Mudskipper"],
        "description": "The largest mangrove forest in the world, where rivers split into a thousand channels and land and water refuse to be separate things. Bengal tigers swim between islands. Dolphins surface in brown water. Mudskippers climb trees. Everything here defies categories. Navigating by boat through endless green corridors, I feel the pulse of a living labyrinth.",
        "feeling": "Disoriented and fascinated",
        "lat": 21.9497, "lng": 89.1833,
    },
    {
        "name": "Pablo Herrera",
        "country": "Chile",
        "place": "Torres del Paine National Park",
        "flora": ["Lenga beech", "Calafate bush", "Antarctic orchid"],
        "fauna": ["Puma", "Guanaco", "Andean condor"],
        "description": "The three granite towers — the Torres — catch the first light of dawn and turn from grey to gold to blazing orange in minutes. Guanacos graze on the steppe below, watched by pumas. Condors ride the thermals above the peaks. The wind in Patagonia is a physical force — it shapes the trees, the lakes, and eventually, you. I feel scoured clean.",
        "feeling": "Stripped bare and renewed",
        "lat": -51.0000, "lng": -73.0000,
    },
    {
        "name": "Nadia Kowalski",
        "country": "Poland",
        "place": "Białowieża Forest",
        "flora": ["Ancient oak", "Hornbeam", "Wood anemone"],
        "fauna": ["European bison", "White-backed woodpecker", "Wolf"],
        "description": "The last primeval forest in lowland Europe. Oaks over 500 years old, trunks too wide to embrace. European bison — brought back from extinction — move through the undergrowth like ghosts from the Pleistocene. Dead trees are left to fall and become cities of fungi and insects. This is what all of Europe once looked like. Walking here is walking backward through time.",
        "feeling": "Time-travelling",
        "lat": 52.7011, "lng": 23.8761,
    },
    {
        "name": "Omar Al-Farsi",
        "country": "United Arab Emirates",
        "place": "Liwa Oasis, Empty Quarter",
        "flora": ["Date palm", "Ghaf tree", "Desert hyacinth"],
        "fauna": ["Arabian oryx", "Sand gazelle", "Pharaoh eagle-owl"],
        "description": "The dunes of the Rub' al Khali rise over 300 metres — the largest sand sea on Earth. At Liwa, the oasis has sustained life for millennia, date palms rising from the sand in defiant green. At sunset, the dunes shift from gold to copper to violet. The silence is total. Arabian oryx, white as bone, move along the dune crests. The desert teaches patience.",
        "feeling": "Still and patient",
        "lat": 23.1167, "lng": 53.7000,
    },
    {
        "name": "Hannah van der Berg",
        "country": "Netherlands",
        "place": "Wadden Sea",
        "flora": ["Glasswort", "Sea aster", "Eelgrass"],
        "fauna": ["Harbour seal", "Spoonbill", "Dunlin"],
        "description": "At low tide, you can walk across the sea floor to the islands — mudflat hiking through a world that exists for only six hours. Seals haul out on sandbars. Millions of migratory birds use this as a refuelling stop. The mudflats stretch to every horizon, gleaming. It is the opposite of dramatic — subtle, shifting, and utterly captivating once you learn to read it.",
        "feeling": "Attuned to subtlety",
        "lat": 53.1100, "lng": 4.9500,
    },
    {
        "name": "Diego Vargas",
        "country": "Colombia",
        "place": "Caño Cristales, Serranía de la Macarena",
        "flora": ["Macarenia clavigera (river plant)", "Moss", "Riverweed"],
        "fauna": ["Howler monkey", "Cock-of-the-rock", "River turtle"],
        "description": "For a few months each year, the river turns into a liquid rainbow — red, yellow, green, blue, and black from aquatic plants, algae, and stone. It's called the River of Five Colours and it looks photoshopped but isn't. Howler monkeys roar from the forest edge. The remoteness — it takes real effort to reach — makes the colours feel like a reward.",
        "feeling": "Rewarded and dazzled",
        "lat": 3.0667, "lng": -73.8833,
    },
    {
        "name": "Maren Haugen",
        "country": "Norway",
        "place": "Svalbard Archipelago",
        "flora": ["Arctic moss", "Svalbard poppy", "Purple saxifrage"],
        "fauna": ["Polar bear", "Arctic fox", "Walrus"],
        "description": "At 78 degrees north, the sun doesn't set for four months, then doesn't rise for four more. Glaciers calve into fjords where walruses rest on ice floes. Polar bears patrol the shore ice. The Svalbard poppy — the northernmost flowering plant — blooms yellow against the grey scree. In the permanent daylight of summer, time loses all meaning. You just exist.",
        "feeling": "Outside of time",
        "lat": 78.0000, "lng": 20.0000,
    },
    {
        "name": "Ravi Krishnamurthy",
        "country": "India",
        "place": "Ladakh, Pangong Lake",
        "flora": ["Juniper", "Seabuckthorn", "Wild rose"],
        "fauna": ["Black-necked crane", "Kiang (wild ass)", "Marmot"],
        "description": "At 4,350 metres, the lake stretches 134 kilometres, changing colour from azure to turquoise to deep indigo as clouds pass overhead. The mountains around it are bare and vast, painted in stripes of red, brown, and grey. Black-necked cranes — sacred in Ladakh — feed at the marshy edges. The thin air makes everything crisp and unreal, like living inside a photograph.",
        "feeling": "Elevated in every sense",
        "lat": 33.7667, "lng": 78.7833,
    },
    {
        "name": "Clara Johansson",
        "country": "Finland",
        "place": "Archipelago National Park",
        "flora": ["Sea buckthorn", "Juniper", "Baltic orchid"],
        "fauna": ["White-tailed eagle", "Baltic ringed seal", "Eider duck"],
        "description": "Thousands of islands and skerries scatter across the Baltic like a broken mosaic. The granite is pink, smoothed by ice ages, and the junipers grow sideways from the wind. White-tailed eagles circle overhead. In midsummer, the sun barely dips below the horizon and the water turns to gold. I sail between islands and feel like I could sail forever.",
        "feeling": "Endlessly free",
        "lat": 59.8000, "lng": 21.6000,
    },
]


def seed():
    with app.app_context():
        db.create_all()

        if Place.query.count() > 0:
            print("Database already has places. Skipping seed.")
            return

        for data in SEED_PLACES:
            place = Place(
                user_id=None,
                author_name=data['name'],
                place_name=data['place'],
                country=data['country'],
                description=data['description'],
                feeling=data['feeling'],
                flora=data['flora'],
                fauna=data['fauna'],
                latitude=data['lat'],
                longitude=data['lng'],
            )
            db.session.add(place)

        db.session.commit()
        print(f"Seeded {len(SEED_PLACES)} places successfully.")


if __name__ == '__main__':
    seed()
